-- Bread pre-orders: the whole schema.
--
-- Netlify applies every netlify/database/migrations/<n>_<slug>/migration.sql
-- in lexical order on deploy; tests apply the same file to an in-process
-- Postgres (PGlite), so this is the single source of truth for the shape of
-- the data. Timestamps that decide anything are written by the application's
-- clock, never by now(), so tests can hold time still.

CREATE TABLE products (
  id             text PRIMARY KEY,
  name           text NOT NULL,
  blurb          text NOT NULL DEFAULT '',
  price_cents    integer NOT NULL CHECK (price_cents > 0),
  daily_capacity integer NOT NULL CHECK (daily_capacity >= 0),
  sort_order     integer NOT NULL DEFAULT 0,
  active         boolean NOT NULL DEFAULT true
);

-- One row per pickup date that has ever been touched (reserved against or
-- blocked). It is also the per-date lock: every write that changes a date's
-- stock takes SELECT ... FOR UPDATE on this row first.
CREATE TABLE pickup_dates (
  date           date PRIMARY KEY,
  blocked_at     timestamptz,
  blocked_reason text,
  created_at     timestamptz NOT NULL DEFAULT now()
);

-- committed = units of this date's orders that are reserved or paid.
-- The CHECK is the guarantee that capacity is never exceeded, whatever the
-- application does. overflow is the owner's explicit "I will bake extra"
-- decision for one date, recorded rather than bypassed.
CREATE TABLE date_inventory (
  date       date NOT NULL REFERENCES pickup_dates (date),
  product_id text NOT NULL REFERENCES products (id),
  capacity   integer NOT NULL CHECK (capacity >= 0),
  overflow   integer NOT NULL DEFAULT 0 CHECK (overflow >= 0),
  committed  integer NOT NULL DEFAULT 0,
  PRIMARY KEY (date, product_id),
  CONSTRAINT date_inventory_within_capacity CHECK (committed >= 0 AND committed <= capacity + overflow)
);

CREATE TABLE orders (
  id              uuid PRIMARY KEY,
  -- Arrival order, for listing; created_at is the clock's word, which tests hold still.
  seq             bigserial NOT NULL UNIQUE,
  date            date NOT NULL REFERENCES pickup_dates (date),
  status          text NOT NULL CHECK (status IN ('reserved', 'paid', 'expired', 'cancelled')),
  customer_name   text NOT NULL CHECK (length(customer_name) BETWEEN 1 AND 80),
  customer_phone  text NOT NULL CHECK (customer_phone ~ '^[0-9]{10}$'),
  total_cents     integer NOT NULL CHECK (total_cents > 0),
  hold_expires_at timestamptz NOT NULL,
  created_at      timestamptz NOT NULL,
  paid_at         timestamptz,
  ended_at        timestamptz,
  picked_up_at    timestamptz,
  forced          boolean NOT NULL DEFAULT false,
  -- Generated by the browser once per "Reserve" tap. A retried request with
  -- the same key returns the same order instead of reserving twice.
  checkout_key    uuid UNIQUE
);
CREATE INDEX orders_date_status ON orders (date, status);
CREATE INDEX orders_status_hold_expires ON orders (status, hold_expires_at);

-- Price is snapshotted here at reservation time; later price changes never
-- touch an existing order.
CREATE TABLE order_items (
  order_id         uuid NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
  product_id       text NOT NULL REFERENCES products (id),
  quantity         integer NOT NULL CHECK (quantity > 0),
  unit_price_cents integer NOT NULL CHECK (unit_price_cents > 0),
  PRIMARY KEY (order_id, product_id)
);

-- One row per attempt to get paid for an order. Today the provider is always
-- 'zelle' and the owner confirms it by hand; a later stage adds 'stripe' with
-- the Checkout Session id as external_id. At most one pending and one
-- succeeded reference per order.
CREATE TABLE payment_references (
  id              bigserial PRIMARY KEY,
  order_id        uuid NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
  provider        text NOT NULL CHECK (provider IN ('zelle', 'stripe')),
  external_id     text,
  idempotency_key text NOT NULL,
  status          text NOT NULL CHECK (status IN ('pending', 'succeeded', 'failed', 'expired')),
  amount_cents    integer NOT NULL CHECK (amount_cents > 0),
  confirmed_by    text,
  created_at      timestamptz NOT NULL,
  updated_at      timestamptz NOT NULL,
  UNIQUE (provider, external_id)
);
CREATE UNIQUE INDEX payment_references_one_pending   ON payment_references (order_id) WHERE status = 'pending';
CREATE UNIQUE INDEX payment_references_one_succeeded ON payment_references (order_id) WHERE status = 'succeeded';
CREATE INDEX payment_references_order ON payment_references (order_id);

-- A temporary reservation is a reserved order. Exposed as its own entity
-- without a second table that could drift from orders.status.
CREATE VIEW reservations AS
  SELECT id AS order_id, date, hold_expires_at AS expires_at, created_at
  FROM orders
  WHERE status = 'reserved';

INSERT INTO products (id, name, blurb, price_cents, daily_capacity, sort_order) VALUES
  ('sourdough', 'Sourdough',    'A full loaf', 500, 3, 1),
  ('banana',    'Banana bread', 'Small loaf',  300, 4, 2);
